# Generated by Django 5.2 on 2025-05-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cvquestionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvquestionnaire',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
