# Generated by Django 5.2 on 2025-05-08 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cvquestionnaire_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_response', to='core.cvquestionnaire')),
            ],
        ),
    ]
