# Generated by Django 5.2.1 on 2025-05-20 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_airesponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvquestionnaire',
            name='user',
        ),
        migrations.DeleteModel(
            name='AIResponse',
        ),
        migrations.DeleteModel(
            name='CVQuestionnaire',
        ),
    ]
