# Generated by Django 5.2.1 on 2025-05-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_plan_user_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='stripe_price_id',
            new_name='stripe_price_id_monthly',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id_yearly',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
