# Generated by Django 5.2.1 on 2025-05-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_plan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_subscription_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
