# Generated by Django 5.2.1 on 2025-05-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='plan',
            name='order',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
