# Generated by Django 5.2.1 on 2025-05-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_plan_options_plan_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_renewal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
