# Generated by Django 5.2.1 on 2025-05-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_renewal_date',
        ),
    ]
