# Generated by Django 5.2.6 on 2025-09-24 12:45

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_user_subscription_renewal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[core.validators.validate_email_with_suggestions], verbose_name='email address'),
        ),
    ]
