name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_KEY }}

      - name: Deploy Changes to Live Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # Navigate to the project directory
            cd /var/www/html/app/api || exit

            # Pull the latest changes from the production branch
            git pull origin main

            # Activate the virtual environment
            source /var/www/html/venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Run database migrations
            python manage.py migrate

            # Restart the application with PM2
            pm2 restart ecosystem.prod.config.js
          EOF
