# Generated by Django 5.2.1 on 2025-05-20 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('experience_level', models.CharField(choices=[('0-2', '0-2 years'), ('3-5', '3-5 years'), ('6+', '6+ years')], max_length=10)),
                ('company_size', models.CharField(choices=[('startup', 'Startup'), ('small', 'Small'), ('medium', 'Medium'), ('enterprise', 'Enterprise')], max_length=10)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('application_timeline', models.CharField(choices=[('immediate', 'Immediate'), ('1-3 months', '1-3 months'), ('3-6 months', '3-6 months'), ('6+ months', '6+ months')], max_length=20)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_response', to='cv.cvquestionnaire')),
            ],
        ),
    ]
