# Generated by Django 5.2.7 on 2025-10-04 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_airesponse_questionnaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='airesponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='airesponse',
            name='response_text',
            field=models.TextField(help_text='ai generated response text'),
        ),
        migrations.AlterField(
            model_name='cvquestionnaire',
            name='application_timeline',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('1-3 months', '1-3 months'), ('3-6 months', '3-6 months'), ('6+ months', '6+ months')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cvquestionnaire',
            name='company_size',
            field=models.CharField(choices=[('startup', 'Startup'), ('small', 'Small'), ('medium', 'Medium'), ('enterprise', 'Enterprise')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cvquestionnaire',
            name='experience_level',
            field=models.CharField(choices=[('0-2', '0-2 years'), ('3-5', '3-5 years'), ('6+', '6+ years')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cvquestionnaire',
            name='industry',
            field=models.CharField(db_index=True, help_text='industry (max 255 characters)', max_length=255),
        ),
        migrations.AlterField(
            model_name='cvquestionnaire',
            name='job_description',
            field=models.TextField(blank=True, help_text='job description (max 5000 characters)', null=True),
        ),
        migrations.AlterField(
            model_name='cvquestionnaire',
            name='location',
            field=models.CharField(blank=True, help_text='location (max 255 characters)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cvquestionnaire',
            name='position',
            field=models.CharField(db_index=True, help_text='job position (max 255 characters)', max_length=255),
        ),
        migrations.AlterField(
            model_name='cvquestionnaire',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='airesponse',
            index=models.Index(fields=['questionnaire', 'created_at'], name='ai_quest_created_idx'),
        ),
        migrations.AddIndex(
            model_name='airesponse',
            index=models.Index(fields=['created_at'], name='ai_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='cvquestionnaire',
            index=models.Index(fields=['user', 'submitted_at'], name='cv_user_submitted_idx'),
        ),
        migrations.AddIndex(
            model_name='cvquestionnaire',
            index=models.Index(fields=['position', 'industry'], name='cv_position_industry_idx'),
        ),
        migrations.AddIndex(
            model_name='cvquestionnaire',
            index=models.Index(fields=['experience_level', 'company_size'], name='cv_exp_company_idx'),
        ),
        migrations.AddIndex(
            model_name='cvquestionnaire',
            index=models.Index(fields=['submitted_at'], name='cv_submitted_at_idx'),
        ),
    ]
